# Generated by Django 5.1.15 on 2026-09-21 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, help_text='Name of the registered backend tool invoked.', max_length=100)),
                ('parameters', models.JSONField(default=dict, help_text='Sanitized JSON parameters passed into the tool.')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Permission Denied'), ('FAILED', 'Execution Error')], help_text='Outcome status of the tool execution attempt.', max_length=20)),
                ('response_summary', models.TextField(blank=True, default='', help_text='Summary or error detail produced by the tool execution.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the tool invocation was recorded.')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who initiated or authorized this AI tool action.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Audit Log',
                'verbose_name_plural': 'Agent Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
