# Generated by Django 5.1.15 on 2026-09-16 11:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name for the product category.', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe slug representation of the category.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed overview of this category.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this category is active and visible for product assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='idx_cat_name_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__exact', ''), _negated=True), name='check_category_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Commercial display name of the product.', max_length=200)),
                ('sku', models.CharField(db_index=True, help_text='Globally unique Stock Keeping Unit identifier.', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Full specifications or commercial description.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit selling price (must be non-negative).', max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Physical units currently in stock.')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Threshold below which low-stock reorder alerts are triggered.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this product is available for inventory operations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The classification group this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='domain_app.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='idx_prod_cat_active'), models.Index(fields=['name'], name='idx_prod_name'), models.Index(fields=['sku'], name='idx_prod_sku'), models.Index(fields=['-created_at'], name='idx_prod_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='check_product_price_non_negative'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='check_product_stock_non_negative'), models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='check_product_reorder_non_negative'), models.CheckConstraint(condition=models.Q(('sku__exact', ''), _negated=True), name='check_product_sku_not_empty')],
            },
        ),
    ]
