# Generated by Django 5.1.15 on 2026-09-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Official company or business name of the supplier.', max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', help_text='Primary contact representative or account manager.', max_length=150)),
                ('email', models.EmailField(db_index=True, help_text='Contact email address for procurement and inquiries.', max_length=254)),
                ('phone', models.CharField(help_text='Direct telephone or mobile contact number.', max_length=50)),
                ('address', models.TextField(blank=True, default='', help_text='Physical office, factory, or warehouse dispatch address.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this supplier is active for inventory operations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_supplier_name'), models.Index(fields=['email'], name='idx_supplier_email'), models.Index(fields=['name', 'is_active'], name='idx_supplier_name_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__exact', ''), _negated=True), name='check_supplier_name_not_empty')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Vendor or manufacturer supplying this product SKU.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='domain_app.supplier'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='idx_prod_supplier'),
        ),
    ]
