# Generated by Django 5.1.15 on 2026-09-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0002_supplier_product_supplier_product_idx_prod_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Stock Added'), ('REMOVE', 'Stock Removed'), ('ADJUSTMENT', 'Stock Adjustment')], db_index=True, help_text='Nature of the stock movement (added, removed, adjustment).', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity units moved or delta adjusted.')),
                ('previous_stock', models.PositiveIntegerField(help_text='Stock quantity immediately prior to this transaction.')),
                ('new_stock', models.PositiveIntegerField(help_text='Stock quantity immediately following this transaction.')),
                ('reference', models.CharField(blank=True, default='', help_text='Reference code or identifier (e.g. PO, receipt, audit tag).', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='Operational explanation or reason for the inventory change.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the transaction was committed.')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='target_stock_level',
            field=models.PositiveIntegerField(blank=True, help_text='Optional target or maximum stock level for inventory replenishment.', null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('target_stock_level__isnull', True), ('target_stock_level__gte', 0), _connector='OR'), name='check_product_target_stock_non_negative'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff or manager who authorized/executed this stock movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(help_text='The product SKU affected by this stock transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='domain_app.product'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', '-created_at'], name='idx_inv_tx_prod_date'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='idx_inv_tx_type_date'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['-created_at'], name='idx_inv_tx_created'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='check_inv_tx_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('previous_stock__gte', 0)), name='check_inv_tx_prev_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('new_stock__gte', 0)), name='check_inv_tx_new_non_neg'),
        ),
    ]
