# Generated by Django 5.1.15 on 2026-09-18 17:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0003_inventorytransaction_product_target_stock_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_identifier', models.CharField(db_index=True, help_text='Globally unique sale/order tracking identifier (e.g. SALE-YYYYMMDD-XXXXXX).', max_length=64, unique=True)),
                ('customer_name', models.CharField(db_index=True, help_text='Full name or business identity of the purchasing customer.', max_length=200)),
                ('customer_email', models.EmailField(blank=True, default='', help_text='Optional customer email address for receipting.', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', help_text='Optional customer contact telephone number.', max_length=50)),
                ('sale_date', models.DateTimeField(db_index=True, help_text='Operational date and time of sale execution.')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('DRAFT', 'Draft'), ('CANCELLED', 'Cancelled')], db_index=True, default='COMPLETED', help_text='Fulfillment and settlement lifecycle status of this sale.', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate sum of all line item subtotals (calculated safely on backend).', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Special instructions, shipping notes, or commercial context.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='System record modification timestamp.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member or sales agent who processed this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of units purchased (must be >= 1).')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Historical unit price snapshot at time of sale.', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Line total computed as quantity * unit_price.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Inventory product item purchased.', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='domain_app.product')),
                ('sale', models.ForeignKey(help_text='Parent sale order transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='domain_app.sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['order_identifier'], name='idx_sale_order_id'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='idx_sale_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='idx_sale_status'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer_name'], name='idx_sale_cust_name'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at'], name='idx_sale_created_at'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-sale_date'], name='idx_sale_status_date'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='check_sale_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('order_identifier__exact', ''), _negated=True), name='check_sale_order_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('customer_name__exact', ''), _negated=True), name='check_sale_customer_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='idx_sale_item_sale_prod'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='idx_sale_item_prod'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='unique_product_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='check_sale_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0.00'))), name='check_sale_item_unit_price_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', Decimal('0.00'))), name='check_sale_item_subtotal_non_neg'),
        ),
    ]
