# Generated by Django 5.1.15 on 2026-09-18 18:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0004_sale_saleitem_sale_idx_sale_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Globally unique procurement order identifier (e.g. PO-YYYYMMDD-XXXXXX).', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received / Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Procurement and intake lifecycle status of this purchase order.', max_length=20)),
                ('order_date', models.DateTimeField(db_index=True, help_text='Date and time when this order was authored or issued.')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Anticipated delivery or fulfillment date from the supplier.', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate sum of all purchase line item subtotals (calculated safely on backend).', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Operational instructions, contract references, or procurement notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='System record modification timestamp.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member, inventory manager, or agent who generated this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Supplier or manufacturer fulfilling this procurement order.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='domain_app.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Units ordered from supplier (must be >= 1).')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Procurement cost per unit charged by supplier.', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Line cost computed as quantity * unit_cost.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Inventory SKU being replenished.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='domain_app.product')),
                ('purchase_order', models.ForeignKey(help_text='Parent purchase order transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='domain_app.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_number'], name='idx_po_order_number'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='idx_po_order_date'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='idx_po_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='idx_po_supplier'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['-created_at'], name='idx_po_created_at'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', '-order_date'], name='idx_po_status_date'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='check_po_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('order_number__exact', ''), _negated=True), name='check_po_order_num_not_empty'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'product'], name='idx_po_item_po_prod'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['product'], name='idx_po_item_prod'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='unique_product_per_purchase_order'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='check_po_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0.00'))), name='check_po_item_unit_cost_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', Decimal('0.00'))), name='check_po_item_subtotal_non_neg'),
        ),
    ]
