# Generated by Django 5.1.15 on 2026-09-18 21:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0005_purchaseorder_purchaseorderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='check_po_order_num_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorderitem',
            name='unique_product_per_purchase_order',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='idx_po_supplier',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='idx_po_status_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who created the purchase order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Special instructions or commercial context.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date when the purchase order was issued.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(db_index=True, help_text='Globally unique purchase order identifier (e.g. PO-YYYYMMDD-XXXX).', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Lifecycle status of the purchase order.', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='Vendor or supplier furnishing the inventory.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='domain_app.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate sum of all line item subtotals.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(help_text='Inventory product item to be purchased.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='domain_app.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(help_text='Parent purchase order.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='domain_app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity of units to purchase (must be >= 1).'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Line total computed as quantity * unit_cost.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Agreed unit cost for the purchase.', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', '-order_date'], name='idx_po_supplier_date'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('order_number__exact', ''), _negated=True), name='check_po_order_number_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='unique_product_per_po'),
        ),
    ]
